import type { Metadata } from "next";
import "./globals.css";
import I18nGate from "@/components/providers/I18nGate";


export const metadata: Metadata = {
  title: "xuexiswmz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="zh-CN"
      className="h-full antialiased"
      data-theme="dark"
    >
      <body className="min-h-full flex flex-col">
        <I18nGate>
          {children}
        </I18nGate>
      </body>
    </html>
  );
}
