import type { Metadata } from "next";
import "./globals.css";
import I18nGate from "@/components/providers/I18nGate";


export const metadata: Metadata = {
  title: "xuexiswmz",
  description: "Generated by create next app",
};

const themeScript = `
  (()=>{
    try{
      const savedTheme = localStorage.getItem("theme")
      const theme = 
        savedTheme === "light" || savedTheme === "dark"
          ? savedTheme
          : window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light"
      document.documentElement.dataset.theme = theme
    }catch {
      document.documentElement.dataset.theme = "light"
    }
  })()
`

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="zh-CN"
      className="h-full antialiased"
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: themeScript
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        <I18nGate>
          {children}
        </I18nGate>
      </body>
    </html>
  );
}
