import type { Metadata } from "next";
import "./globals.css";
import I18nGate from "@/components/providers/I18nGate";
import Headers from "@/components/Headers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "xuexiswmz",
  description: "Generated by create next app",
};

const themeScript = `
  (()=>{
    try{
      const savedTheme = localStorage.getItem("theme")
      const theme = 
        savedTheme === "light" || savedTheme === "dark"
          ? savedTheme
          : window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light"
      document.documentElement.dataset.theme = theme
    }catch {
      document.documentElement.dataset.theme = "light"
    }
  })()
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN" className="h-full antialiased" suppressHydrationWarning>
      <head>
        <link rel="stylesheet" href="/text-annotations.css" />
        <script
          dangerouslySetInnerHTML={{
            __html: themeScript,
          }}
        />
      </head>
      <body className="h-dvh overflow-hidden flex flex-col">
        <I18nGate>
          <div className="mx-auto flex h-full min-h-0 w-[94%] max-w-[1600px] flex-col sm:w-[90%]">
            <Headers />
            <main className="min-h-0 flex-1 overflow-y-auto scrollbar-hide">
              {children}
            </main>
          </div>
        </I18nGate>

        <Toaster position="top-center" richColors closeButton />
      </body>
    </html>
  );
}
